### PR TITLE
Add Pinterest Tag Template

### PR DESCRIPTION
**Pull request by Aaronkala**
part of https://github.com/getelevar/elevar-monorepo/issues/35

**Adds Pinterest template tag**

I added a new account in GTM a while back called `Elevar Monitoring Templates`. It contains a container called `Template Development` and that's where I've been developing the templates. You can take a look at the templates there and preview the code for this template also.

This also contains a bunch of unit tests to verify basic functionality and that the code should work. I haven't tested this on an actual site, but the functionality is the same as for "facebook" and "snapchat" templates so I don't see any issues why it wouldn't work if the Pinterest script is called "pintrk".

The template communicates to the core tag in the exact same way as FB and SC (pushing tag information to an array in the window).

Here's the docs for the Pinterest script: https://help.pinterest.com/en-gb/business/article/base-code.

---

Similar to 'facebook' and 'snapchat', this template does not inject the Pinterest script. It has to be injected on the page for this to work.

One difference to the facebook and snapchat templates is that this injects also the `load` event and it doesn't require a separate tag, whereas the FB and sc tags require another tag for the `load` events.

---

I also included all the required files and setup for the template gallery.

### CODE REVIEW

**Comment by Aaronkala** [comment]
> Should all of the brand details be updated?

From what I understood they want the categories to be added: https://developers.google.com/tag-manager/templates/gallery#prepare_your_project_files

> Should we be including the script if it doesn't exist on the page?

Yeah, we probably should. I just did this for Criteo, I'll add it to this one also. We will have to update FB and SC later.

**Comment by Aaronkala** [comment]
@twslade I can't seem to get the script injection to work for the Pinterest tag...

The base script has this setup function before the script is injected (https://help.pinterest.com/en-gb/business/article/base-code), the script doesn't seem to work without it.
```javascript
if (!window.pintrk) {
    window.pintrk = function () {
      window.pintrk.queue.push(Array.prototype.slice.call(arguments));
    };
    ...
}
```

But with the functions that are available in the templates this is a little trickier to achieve.

```javascript
const pintrk = copyFromWindow("pintrk");
if (typeof pintrk === 'undefined') {
  setInWindow("pintrk", function() { /* push arguments to self.queue */ });
}
```

I've been trying to figure it out for some time now but can't seem to get it to work, so if you have any ideas how it could be done let me know.

**Comment by twslade** [comment]
@bradredding82 for all of these templates we are creating:
- Facebook
- Snapchat
- Criteo
- etc

Is the assumption that the base script already exists on the page or we should be injecting that base script as well? I'm slightly confused as to why we wouldn't be including the base script because the template won't work on its own.

---

@Aaronkala I would think the injection would look something like [this](https://github.com/sahava/GoogleTagManagerTemplates/blob/3c80a94fd366ea5f80762b09756f5e86defc3022/tags/Snapchat/SnapPixel/Snap%20Pixel.tpl#L466) using the `injectScript` function.

**Comment by Aaronkala** [comment]
> @Aaronkala I would think the injection would look something like this using the injectScript function.

@twslade Sorry if I worded that confusingly. I have that injection there also, but Pinterest requires that you init the `pintrk` function before injecting the script. The script alone doesn't do anything if the function hasn't been initialized.

The line before the `injectScript` is what needs to be modified.

```javascript
if (typeof pintrk === 'undefined') {
  setInWindow("pintrk", function() { /* push arguments to self.queue */ });
  injectScript(SCRIPT_URL, callEvents, () => data.gtmOnFailure());
} else {
```

---

> Is the assumption that the base script already exists on the page or we should be injecting that base script as well? I'm slightly confused as to why we wouldn't be including the base script because the template won't work on its own.

Yeah... It was my bad choice initially and now I agree with you that they should be injected by the template. I think I was thinking in function land where one function does only one thing.

**Comment by twslade** [comment]
@Aaronkala after chatting with Brad, we definitely need to inject these scripts. These should be installable and handle everything without additional tags and/or code changes.

@bradredding82 feel free to chime in if I missed anything.

**Comment by bradredding82** [comment]
@twslade - correct.

@Aaronkala - when reviewing Snapchat on a snow a few weeks ago I noticed their pageview count dropped significantly. This was due to the global script being paused (that was still in a custom html tag). Once I unpaused this then things went back to normal. I think we slacked about this but let me know if you need anything else on this!

**Pull request closed without merging**
